abstract into functions with comments

diff --git a/whoiam b/whoiam
--- a/whoiam
+++ b/whoiam
@@ -5,17 +5,35 @@
 # ./whoiam www.google.com
 # ./whoiam www.google.com 114.114.114.114
 
-IP_REG='^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'
-if [[ -z $2 ]]; then
-  IPS=$(dig $1 +noall +answer +short) 
-else
-  IPS=$(dig @$2 $1 +noall +answer +short) 
+# print program usage
+usage() {
+    echo "Usage: ./whoiam [domain] [dns ip]"
+}
+
+
+# who is the domain from dns point of view
+who() {
+    IP_REG='^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'
+    if [[ -z $2 ]]; then
+      IPS=$(dig $1 +noall +answer +short) 
+    else
+      IPS=$(dig @$2 $1 +noall +answer +short) 
+    fi
+     
+    for ip in $IPS; do
+      if [[ $ip =~ $IP_REG ]]; then
+        echo "$1 has IP $ip"
+        INFO=$(whois $ip)
+        echo "$INFO"
+      fi
+    done
+}
+
+# begin: program entry
+if [[ "$#" -ne 1 && "$#" -ne 2 ]]; then
+    echo "Error: Illegal number of parameters"
+    usage
+    exit 1
 fi
- 
-for ip in $IPS; do
-  if [[ $ip =~ $IP_REG ]]; then
-    echo "$1 has IP $ip"
-    INFO=$(whois $ip)
-    echo "$INFO"
-  fi
-done
+who $1 $2
+# end: program entry
